# SPDX-FileCopyrightText: 2026 Vibe Coded Emulator contributors
# SPDX-License-Identifier: GPL-3.0-or-later
import pathlib
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[1]
PLAYER = (ROOT / "static/player.js").read_text(encoding="utf-8")
NDS_TOUCH = (ROOT / "static/nds-touch.js").read_text(encoding="utf-8")
OFFLINE = (ROOT / "static/offline.js").read_text(encoding="utf-8")
SITE_JS = (ROOT / "static/site.js").read_text(encoding="utf-8")
SERVICE_WORKER = (ROOT / "static/service-worker.js").read_text(encoding="utf-8")
APP = (ROOT / "app.py").read_text(encoding="utf-8")


class RegressionInvariantTests(unittest.TestCase):
    def test_admin_progress_and_analytics_respect_normal_csp(self):
        # ROM upload/edit and bulk upload were removed from the dashboard.
        self.assertNotIn('id="adminProgress" class="upload-progress"', APP)
        self.assertNotIn('id="bulkProgress" class="upload-progress"', APP)
        # The dashboard tracks visits and app downloads only; play/player
        # analytics must not return.
        self.assertIn('class="reference-line-chart"', APP)
        self.assertIn('data-series=', APP)
        self.assertIn('"Total Visits"', APP)
        self.assertIn('"App Downloads"', APP)
        self.assertIn('class="range-selector"', APP)
        self.assertNotIn('most-played', APP)
        self.assertNotIn('style="height:', APP)
        self.assertNotIn("bar.style.width", SITE_JS)

    def test_nds_uses_melonds_auto_start_and_touch_bridge(self):
        self.assertIn('nds:"melonds"', PLAYER)
        self.assertIn("window.EJS_startOnLoaded = true", PLAYER)
        self.assertIn('retroarch_core:"melonds"', PLAYER)
        self.assertIn('window.EJS_disableLocalStorage = ndsPad', PLAYER)
        self.assertIn('canvas.classList.remove("ejs-canvas-no-pointer")', PLAYER)
        self.assertIn('setProperty("pointer-events","auto","important")', PLAYER)
        self.assertIn('setProperty("touch-action","none","important")', PLAYER)
        self.assertIn("const queueCanvasProtection=()=>", PLAYER)
        self.assertIn("new MutationObserver(queueCanvasProtection)", PLAYER)
        self.assertIn("new MutationObserver(mutations=>{if(mutations.some(mutationTouchesEmulatorMenu))queueEmulatorMenuLayer();})", PLAYER)
        self.assertIn("dispatchNdsMouse", PLAYER)
        self.assertIn("getBoundingClientRect", PLAYER)
        self.assertIn('Object.defineProperty(event,name', PLAYER)
        self.assertIn('"offsetX"', PLAYER)
        self.assertIn('"offsetY"', PLAYER)
        self.assertIn('new URLSearchParams(location.search).get("touch")', PLAYER)
        self.assertIn('get("touch") || "geometry-mapped"', PLAYER)
        self.assertIn('["native","root","root-touch","overlay","hybrid-root","geometry-only","geometry-mapped"]', PLAYER)
        self.assertIn('elementFromPoint(event.clientX,event.clientY)', PLAYER)
        self.assertIn('resolveSourceCanvas?.(gameRoot,hit,path)', PLAYER)
        self.assertIn('isProtectedUiTarget?.(gameRoot,event.target,path)', PLAYER)
        self.assertIn('if (protectedUi) return;', PLAYER)
        self.assertIn('let releaseRootNdsTouch=()=>{};', PLAYER)
        self.assertIn('releaseRootNdsTouch("emulator-menu-open")', PLAYER)
        self.assertIn('addEventListener("blur",()=>releaseRootNdsTouch("window-blur")', PLAYER)
        self.assertIn('document.addEventListener("visibilitychange",()=>{if(document.hidden)releaseRootNdsTouch("document-hidden");}', PLAYER)
        self.assertIn('document.addEventListener("fullscreenchange",()=>releaseRootNdsTouch("fullscreen-change")', PLAYER)
        self.assertIn('isProtectedUiEvent(event)', PLAYER)
        self.assertIn('canvas:not(.an3-render-canvas)', PLAYER)
        root_touch_block = PLAYER[PLAYER.index("const bindRootNdsTouch"):PLAYER.index("const protectNdsCanvas")]
        self.assertNotIn('|| gameRoot.querySelector("canvas")', root_touch_block)
        self.assertIn('createTouchGestureOwner?.({', PLAYER)
        self.assertIn('createTapReleaseLatch?.()', PLAYER)
        self.assertIn('state.releaseState="latched-next-input-frame"', PLAYER)
        self.assertIn('tapRelease.defer(state,()=>sendRelease(state))', PLAYER)
        self.assertIn('tapRelease?.flush?.()', PLAYER)
        self.assertIn('Object.defineProperty(event,"pointerType",{value:"touch"', PLAYER)
        self.assertIn('const shieldSyntheticNdsMouseFromMenu', PLAYER)
        self.assertIn('!event.isTrusted && event.pointerType === "touch"', PLAYER)
        self.assertIn('event.stopPropagation()', PLAYER)
        self.assertIn('shieldSyntheticNdsMouseFromMenu(canvas)', PLAYER)
        self.assertIn('return dispatchNdsMouse(canvas, type, source, buttons);', PLAYER)
        self.assertIn('const activeTouchId=()=>owner?.active?.()?.id ?? null;', PLAYER)
        self.assertIn('startedAt:performance.now(),moveCount:0', PLAYER)
        self.assertIn('gameRoot.setPointerCapture(event.pointerId)', PLAYER)
        self.assertIn('!["touch","touch-passive","pointer-touch","hybrid"].includes(touchVariant)', PLAYER)
        self.assertIn('event.touches||[]', PLAYER)
        self.assertIn('document.addEventListener("touchmove",move', PLAYER)
        self.assertIn('touchVariant === "touch-passive"', PLAYER)
        self.assertIn('touchVariant === "pointer-no-capture"', PLAYER)
        self.assertIn('["delta","geometry-only","geometry-mapped"].includes(touchVariant)', PLAYER)
        self.assertIn('touchVariant === "pointer-touch"', PLAYER)
        self.assertIn('["hybrid","hybrid-root","geometry-only","geometry-mapped"].includes(touchVariant)', PLAYER)
        self.assertIn('["root-touch","hybrid-root","geometry-only","geometry-mapped"].includes(touchVariant)', PLAYER)
        self.assertIn('const isolatedNdsMovement = ["geometry-only","geometry-mapped"].includes(touchVariant)', PLAYER)
        self.assertIn('"__an3NdsLastMousePoint"', PLAYER)
        self.assertIn('"__an3NdsLastPointerPoint"', PLAYER)
        self.assertIn('const pointKey=isolatedNdsMovement', PLAYER)
        self.assertIn('const mapNdsCursor =', PLAYER)
        self.assertIn('gl?.getParameter(gl.VIEWPORT)', PLAYER)
        self.assertIn('raw[0]+raw[2]<=backingWidth', PLAYER)
        self.assertIn('raw[1]+raw[3]<=backingHeight', PLAYER)
        self.assertIn('movementX=mapped.x-ndsMappedCursor.x', PLAYER)
        self.assertIn('movementY=mapped.y-ndsMappedCursor.y', PLAYER)
        self.assertIn('if (type === "mousedown") ndsViewportCache.delete(canvas)', PLAYER)
        hybrid_block = PLAYER[PLAYER.index('if (["hybrid","hybrid-root","geometry-only","geometry-mapped"]'):PLAYER.index('dispatchNdsMouse(canvas, type, source, buttons);', PLAYER.index('if (["hybrid","hybrid-root","geometry-only","geometry-mapped"]')) + len('dispatchNdsMouse(canvas, type, source, buttons);')]
        self.assertLess(hybrid_block.index("dispatchNdsPointer"), hybrid_block.index("dispatchNdsMouse"))
        self.assertIn('...(touchVariant === "core-touch" ? {melonds_touch_mode:"Touch"} : {})', PLAYER)
        self.assertNotIn('touchVariant === "geometry-mapped" ? {melonds_touch_mode', PLAYER)
        self.assertNotIn("desmume", PLAYER.lower())
        self.assertNotIn("startButtonClicked", PLAYER)
        self.assertIn('new URL(event.request.url).pathname', SERVICE_WORKER)
        self.assertIn('an3-arcade-pwa-v31-__ASSET_VERSION__', SERVICE_WORKER)
        self.assertIn('/static/v/__ASSET_VERSION__/player-runtime.js', SERVICE_WORKER)
        self.assertIn('/static/v/__ASSET_VERSION__/nds-touch.js', SERVICE_WORKER)
        self.assertIn('/static/v/__ASSET_VERSION__/offline.js', SERVICE_WORKER)
        self.assertIn('/static/v/__ASSET_VERSION__/site.css', SERVICE_WORKER)
        self.assertIn('/static/default-cover.webp', SERVICE_WORKER)
        self.assertIn('/static/default-cover.webp', APP)
        self.assertIn('const createTapReleaseLatch', NDS_TOUCH)
        self.assertIn('scheduleFrame || (callback => globalThis.requestAnimationFrame(callback))', NDS_TOUCH)
        self.assertIn('candidate.handle = schedule(() => finish(candidate))', NDS_TOUCH)
        self.assertIn('createTapReleaseLatch', NDS_TOUCH)

    def test_virtual_controls_overlay_has_persistent_touch_toggle_and_safe_global_scale(self):
        for source in (APP, OFFLINE):
            self.assertIn('id="toggleTouch"', source)
            self.assertIn('id="padGlobalScale"', source)
            self.assertIn('id="padGlobalScaleValue"', source)
            self.assertIn('id="resetPadGlobalScale"', source)
            self.assertIn('class="player-pad-advanced"', source)
            self.assertIn('id="padTarget"', source)
            self.assertIn('id="padSize" type="range" min="50" max="200" step="1"', source)
            self.assertIn('id="padSizeValue"', source)
            self.assertIn('id="padSizeHint"', source)
            self.assertIn('id="resetPadTarget"', source)
            self.assertIn('id="resetPadSizes"', source)
            self.assertIn('id="resetPadLayout"', source)
        self.assertIn('touchToggle?.addEventListener("click",togglePad)', PLAYER)
        self.assertIn('const requested=clamp(Number(next) || 1,.7,1),current=globalScale();', PLAYER)
        self.assertIn('const buttonScale = id => normalizeButtonScale(settings.buttonScales[id]);', PLAYER)
        self.assertIn('const controlScale = id => globalScale()*baseControlScale(id)*buttonScale(id);', PLAYER)
        self.assertIn('const oldScale=clamp(Number(old.sizes[id] ?? old.scale) || 1,.7,1.4);', PLAYER)
        self.assertIn('const scale=normalizeButtonScale(oldScale/baseControlScale(id));', PLAYER)
        self.assertIn('--control-scale', PLAYER)
        self.assertIn('const controlBounds = element => {', PLAYER)
        self.assertIn('control=element.getBoundingClientRect()', PLAYER)
        self.assertNotIn('element.firstElementChild?.getBoundingClientRect()', PLAYER)
        self.assertIn('const constrainedPosition = (element,point) => {', PLAYER)
        self.assertIn('const renderedControlScale = element => {', PLAYER)
        self.assertIn('const predictedControlRect = (element, multiplier=buttonScale(element.dataset.id), options={}) => {', PLAYER)
        self.assertIn('const rectsConflict = (first,second) =>', PLAYER)
        self.assertIn('const inspectButtonScales = (overrides={}, options={}) => {', PLAYER)
        self.assertIn('padRoot.querySelectorAll(".tvCtrl")', PLAYER)
        self.assertIn('const commitButtonScale = (id, next) => {', PLAYER)
        self.assertIn('commitButtonScale(padTarget.value,1)', PLAYER)
        self.assertIn('document.getElementById("resetPadSizes")?.addEventListener("click",resetAllButtonScales);', PLAYER)
        self.assertIn('document.getElementById("resetPadLayout")?.addEventListener("click",resetCurrentLayout);', PLAYER)
        self.assertIn('const commitGlobalScale = next => {', PLAYER)
        self.assertIn('inspectCurrentButtonScales({globalScale:requested})', PLAYER)
        self.assertIn('const candidate={...padDefaults[orientation]};', PLAYER)
        self.assertIn('inspectCurrentButtonScales({positions:candidate})', PLAYER)
        self.assertIn('let padSafetyBlocked=false;', PLAYER)
        self.assertIn('const checkCurrentPadSafety = () => {', PLAYER)
        self.assertIn('padRoot.classList.remove("safety-blocked");', PLAYER)
        self.assertNotIn('#tvPad.show.safety-blocked', (ROOT / "static/site.css").read_text(encoding="utf-8"))
        self.assertIn('const safety=applySettings();if(!safety.safe)reportPadSafety(safety);', PLAYER)
        self.assertIn('document.addEventListener("fullscreenchange",queuePadLayout)', PLAYER)
        self.assertIn('stage?.classList.toggle("pad-overlay",visible);', PLAYER)
        self.assertNotIn('stage?.classList.toggle("pad-docked",visible)', PLAYER)
        self.assertIn('window.EJS_emulator?.gameManager?.simulateInput(0,index,value)', PLAYER)
        self.assertIn('visibilityMode:"auto"', PLAYER)
        self.assertIn('const touchFirst = Boolean(!window.matchMedia?.("(hover:hover)")?.matches && (window.matchMedia?.("(pointer:coarse)")?.matches || navigator.maxTouchPoints > 0));', PLAYER)
        self.assertIn('window.EJS_noAutoFocus = ndsPad && touchFirst', PLAYER)
        self.assertIn('if (ndsPad && result.visible===false && !["auto","shown","hidden"].includes(result.visibilityMode)) result.visibilityMode="hidden";', PLAYER)
        self.assertIn('const wasVisible=padVisible();if(ndsPad)settings.visibilityMode=wasVisible?"hidden":"shown"', PLAYER)
        self.assertIn('stage?.classList.toggle("emulator-menu-open",menuOpen)', PLAYER)
        self.assertIn('emulatorMenuTimer=setTimeout(syncEmulatorMenuLayer,250)', PLAYER)
        self.assertIn('const setPadEditing = (editing,{force=false}={}) => {', PLAYER)
        self.assertIn('if (editing && !padVisible()) {', PLAYER)
        self.assertIn('if (editing && (ndsPad || threeDsPad)) {', PLAYER)
        self.assertIn('panel?.classList.remove("open");', PLAYER)
        self.assertIn('if (!editing) saveLayout();', PLAYER)
        self.assertIn('const up=()=>{saveLayout();', PLAYER)
        self.assertIn('Drag placement is deliberately free-form.', PLAYER)
        self.assertIn('const threeDsDefaults = {', PLAYER)
        self.assertIn('portrait:{dpad:{x:19,y:79},a:{x:87,y:78.5},b:{x:73,y:88.5},x:{x:89,y:55},y:{x:74,y:69},l:{x:15,y:52},r:{x:85,y:45},start:{x:39,y:61},select:{x:62,y:61}}', PLAYER)
        self.assertIn('landscape:{...defaults.landscape,r:{x:87,y:20}}', PLAYER)
        self.assertIn('an3-pad-v${ndsPad ? 5 : threeDsPad ? 7 : 3}', PLAYER)
        self.assertIn('config.system === "3ds" ? "data-v2" : "data"', PLAYER)
        self.assertIn('data(?:-v[1-9][0-9]*)?', APP)
        site_css = (ROOT / "static/site.css").read_text(encoding="utf-8")
        self.assertIn('.player-page .player-stage-ui.emulator-menu-open #tvPad.show', site_css)
        self.assertIn('.player-page .player-stage-ui.emulator-menu-open #tvPad.show .tvCtrl{pointer-events:none}', site_css)

    def test_performance_profiles_are_conservative_and_persisted(self):
        self.assertIn('const performanceStorageKey = "an3-player-performance-v1"', PLAYER)
        self.assertIn('version:1,', PLAYER)
        self.assertIn('selectedProfile:normalizeProfileId(storedPerformance.selectedProfile)', PLAYER)
        self.assertIn('customOverrides:{', PLAYER)
        self.assertIn('const recommendedProfile = recommendPerformanceProfile(capabilityProbe);', PLAYER)
        self.assertIn('return "balanced";', PLAYER)
        self.assertIn('probe.deviceMemory && probe.deviceMemory<=2 && probe.hardwareConcurrency && probe.hardwareConcurrency<=4', PLAYER)
        self.assertIn('(ndsPad && !probe.webgl2)', PLAYER)
        self.assertIn('window.EJS_forceLegacyCores = performancePlan.forceLegacyNds;', PLAYER)
        self.assertIn('const coreUsesWebgl2=!performancePlan.forceLegacyNds', PLAYER)
        self.assertIn('fps:"show",', PLAYER)
        self.assertIn('window.EJS_disableLocalStorage = ndsPad || threeDsPad;', PLAYER)
        self.assertNotIn('frameskip', PLAYER.lower())
        self.assertNotIn('render_scale', PLAYER.lower())
        for source in (APP, OFFLINE):
            self.assertIn('name="performanceProfile" value="auto"', source)
            self.assertIn('name="performanceProfile" value="low"', source)
            self.assertIn('name="performanceProfile" value="balanced"', source)
            self.assertIn('name="performanceProfile" value="quality"', source)
            self.assertIn('name="performanceProfile" value="custom"', source)
            self.assertIn('id="useRecommended"', source)
            self.assertIn('id="applyPerformanceProfile"', source)

    def test_3ds_preload_uses_the_required_webgl2_bundle_and_netplay_is_staging_opt_in(self):
        self.assertIn('report?.options?.requiresWebgl2', PLAYER)
        self.assertIn('const coreCapabilityError = () => {', PLAYER)
        self.assertIn('window.EJS_gameID = config.netplayGameId || config.slug;', PLAYER)
        self.assertIn('window.EJS_netplayServer = config.netplayServer || undefined;', PLAYER)
        self.assertIn('window.EJS_netplayICEServers = config.netplayServer ? [] : undefined;', PLAYER)
        self.assertIn('melonds_screen_layout:dualScreenLayout()', PLAYER)
        self.assertIn('citra_layout_option:dualScreenLayout()==="Left/Right"?"side_by_side":"default"', PLAYER)
        self.assertIn('Restart the player to apply the ${desiredNdsLayout} 3DS screen layout.', PLAYER)
        self.assertIn('Restart the player to apply the ${desiredNdsLayout} DS screen layout.', PLAYER)
        self.assertIn('NETPLAY_ORIGIN = (', APP)
        self.assertIn('ENVIRONMENT in {"staging", "development"}', APP)
        self.assertIn('"netplayServer": NETPLAY_ORIGIN', APP)
        # CSP connect-src treats ws:/wss: as distinct schemes; the player must
        # allow the relay's WebSocket or the Socket.IO upgrade is blocked.
        self.assertIn("def player_content_security_policy(netplay_origin):", APP)
        self.assertIn('netplay_connect += " " + netplay_origin.replace("http://", "ws://", 1)', APP)
        self.assertIn('netplay_connect += " " + netplay_origin.replace("https://", "wss://", 1)', APP)
        self.assertIn("csp = player_content_security_policy(NETPLAY_ORIGIN)", APP)
        # The multiplayer room -> relay bridge is a staging-only player panel.
        self.assertIn('"multiplayerEnabled": MULTIPLAYER_ENABLED', APP)
        self.assertIn('"roomSignature": {', APP)
        self.assertIn('id="mpPlayerPanel"', APP)
        self.assertIn('id="playerMultiplayer"', APP)
        self.assertIn('netplay.openRoom(code, 2, "")', PLAYER)
        self.assertIn('netplay.joinRoom(key, data.code)', PLAYER)

    def test_player_keeps_input_order_and_persists_drag_until_done(self):
        self.assertIn('const dualScreenLayout = () => innerWidth > innerHeight ? "Left/Right" : "Top/Bottom";', PLAYER)
        self.assertIn('the toolbar/menu remains above the', PLAYER)
        self.assertIn('"lostpointercapture"', PLAYER)
        self.assertIn('then reopen the player menu and choose Done to lock their positions.', PLAYER)
        self.assertIn('id="castScreen"', APP)
        self.assertIn('id="castScreen"', OFFLINE)
        self.assertIn('const castGameToTv=async()=>', PLAYER)
        self.assertIn('canvas.captureStream(60)', PLAYER)
        self.assertIn('video.remote.watchAvailability', PLAYER)
        self.assertIn('stage?.classList.add("tv-console-mode")', PLAYER)
        self.assertIn('cast-console-show', PLAYER)
        self.assertIn('.player-stage-ui.tv-console-mode #game', (ROOT / "static/site.css").read_text(encoding="utf-8"))

    def test_speed_controls_are_session_only_and_runtime_gated(self):
        self.assertIn('window.EJS_hideSettings = ["fastForward","ff-ratio","slowMotion","sm-ratio"];', PLAYER)
        self.assertIn('const speedSteps=Object.freeze([.5,1,1.5,2]);', PLAYER)
        self.assertIn('const speedManager = () => {', PLAYER)
        self.assertIn('return gameStarted && manager && required.every', PLAYER)
        self.assertIn('manager.setFastForwardRatio(value);', PLAYER)
        self.assertIn('manager.toggleFastForward(1);', PLAYER)
        self.assertIn('manager.setSlowMotionRatio(1/value);', PLAYER)
        self.assertIn('manager.toggleSlowMotion(1);', PLAYER)
        self.assertIn('manager.toggleFastForward(0);', PLAYER)
        self.assertIn('manager.toggleSlowMotion(0);', PLAYER)
        self.assertNotIn('an3-player-speed', PLAYER)
        self.assertIn('id="speedDown"', APP)
        self.assertIn('id="speedUp"', APP)
        self.assertIn('id="speedValue"', APP)
        self.assertIn('const speedSettingsMarkup = system => {', OFFLINE)
        self.assertIn('speedSettingsMarkup(system)', OFFLINE)

    def test_player_options_are_grouped_and_available_to_every_emulator(self):
        for source in (APP, OFFLINE):
            self.assertIn('player-performance-settings', source)
            self.assertIn('player-speed-settings', source)
            self.assertIn('player-controls-settings', source)
            self.assertIn('player-game-settings', source)
            self.assertIn('player-advanced-settings', source)
            self.assertIn('id="togglePad"', source)
            self.assertIn('id="emulatorMenu"', source)
            self.assertIn('id="saveState"', source)
            self.assertIn('id="loadState"', source)
        self.assertIn('const touchToggleMarkup = system => ["gb","gba","nds","3ds"].includes(system)', OFFLINE)
        self.assertIn('game["system"] in {"gb", "gba", "nds", "3ds"}', APP)
        self.assertNotIn('insertAdjacentHTML("beforebegin",speedSettingsMarkup(system))', OFFLINE)
        self.assertIn('const panelTouchToggle = document.getElementById("togglePad");', PLAYER)
        self.assertIn('const closePlayerOptions = () =>', PLAYER)
        self.assertIn('const closeSlotOptions = () =>', PLAYER)
        self.assertIn('if(stage?.classList.contains("emulator-menu-open"))', PLAYER)
        self.assertIn('new MutationObserver(()=>{if(stage.classList.contains("emulator-menu-open"))closePlayerOptions();})', PLAYER)
        self.assertIn('stage?.classList.toggle("emulator-menu-open",menuOpen)', PLAYER)
        self.assertIn('new MutationObserver(mutations=>{if(mutations.some(mutationTouchesEmulatorMenu))queueEmulatorMenuLayer();})', PLAYER)
        self.assertIn('closePlayerOptions();try{window.EJS_emulator?.menu?.toggle()}catch(_){}queueEmulatorMenuLayer();', PLAYER)
        self.assertIn('document.getElementById("playerControls")?.addEventListener("click",event=>{showHints();if(!panel)return;', PLAYER)
        self.assertNotIn('if(customPad){if(slotPanel)', PLAYER)
        site_css = (ROOT / "static/site.css").read_text(encoding="utf-8")
        self.assertIn('.player-settings-group .player-panel-actions', site_css)
        self.assertIn('.player-page .player-stage-ui.emulator-menu-open #tvPad.show', site_css)
        self.assertIn('.player-page .player-stage-ui.emulator-menu-open #tvPad.show .tvCtrl{pointer-events:none}', site_css)

    def test_fullscreen_keeps_the_app_toolbar_and_status_in_scope(self):
        self.assertIn('else shell.requestFullscreen?.();', PLAYER)
        self.assertNotIn('stage.requestFullscreen?.()', PLAYER)
        self.assertIn('.player-page .player-shell:fullscreen', (ROOT / "static/site.css").read_text(encoding="utf-8"))

    def test_player_runtime_keeps_renderer_and_state_business_logic_outside_the_canvas_adapter(self):
        runtime = (ROOT / "static/player-runtime.js").read_text(encoding="utf-8")
        for name in ("EmulatorSession", "EmulatorCore", "VideoSource", "VideoBackend", "InputRouter", "AudioPipeline", "SaveStateManager", "QuickSaveManager"):
            self.assertIn(f"class {name}", runtime)
        self.assertIn('const rendererValues = new Set(["webgpu", "webgl2"])', runtime)
        self.assertIn('The bundled EmulatorJS runtime currently creates and owns a WebGL', runtime)
        self.assertIn('const QUICK_SAVE_DATABASE = "an3-arcade-save-slots"', runtime)
        self.assertIn('state: new Blob([bytes], {type: "application/octet-stream"})', runtime)
        self.assertIn('supports: Object.freeze(["SoftwareFramebuffer", "NativeGpuFrame"])', runtime)
        self.assertIn('playerSession?.saveStateManager.exportBytes()', PLAYER)
        self.assertIn('playerSession.inputRouter.setVirtualButton(index, value)', PLAYER)
        self.assertIn('const rendererPlan = playerSession?.videoBackend', PLAYER)
        self.assertIn('if (config.mode !== "preload") queueTvDiscovery();', PLAYER)
        self.assertLess(APP.index('versioned_player_asset("player-runtime.js")'), APP.index('versioned_player_asset("player.js")'))

    def test_nds_default_pad_matches_approved_portrait_layout(self):
        self.assertIn('portrait:{dpad:{x:23.4,y:81.6},a:{x:89,y:80},b:{x:78.2,y:89.7},x:{x:78,y:70.2},y:{x:67.3,y:79.9},l:{x:8.1,y:63.3},r:{x:91.2,y:62.5},start:{x:47.4,y:62.1},select:{x:57.9,y:62}}', PLAYER)
        self.assertIn('{version:4,globalScale:1,opacity:.48,visibilityMode:"auto",buttonScales:{}}', PLAYER)
        self.assertIn('{scale:1,opacity:.48,visibilityMode:"auto",sizes:{dpad:1.4,start:.7,select:.7}}', PLAYER)
        self.assertIn('const baseControlScale = id => ndsPad ? ({dpad:1.4,start:.7,select:.7}[id] || 1) : 1;', PLAYER)
        self.assertIn('const settingsKey = ndsPad ? "an3-pad-settings-v4:nds" : threeDsPad ? "an3-pad-settings-v1:3ds" : "an3-pad-settings-v2";', PLAYER)
        self.assertIn('id="padOpacity" type="range" min="30" max="100" step="1"', APP)
        self.assertIn('id="padOpacity" type="range" min="30" max="100" step="1"', OFFLINE)
        self.assertIn('const old={...legacyDefaults,...source,sizes:{...legacyDefaults.sizes,...(isRecord(source.sizes) ? source.sizes : {})}};', PLAYER)
        self.assertIn('const hasCurrentSettings = Number(storedSettings.version) === settingsVersion;', PLAYER)
        self.assertIn('const settings = hasCurrentSettings ? normalizeSettings(storedSettings) : migrateSettings(legacySettings);', PLAYER)

    def test_nds_debug_is_bounded_exportable_and_fail_closed(self):
        self.assertIn('NDS_DEBUG_ALLOWED = ENVIRONMENT in {"staging", "development"}', APP)
        self.assertIn('"ndsDebugAllowed": NDS_DEBUG_ALLOWED', APP)
        self.assertIn('config.ndsDebugAllowed === true && new URLSearchParams(location.search).get("ndsdebug") === "1"', PLAYER)
        self.assertIn('const NDS_DEBUG_LIMIT = 160', PLAYER)
        self.assertIn('ndsDebugEvents.splice(0,ndsDebugEvents.length-NDS_DEBUG_LIMIT)', PLAYER)
        self.assertIn('window.AN3NdsDebug=Object.freeze', PLAYER)
        self.assertIn('exportJSON', PLAYER)
        self.assertIn('{capture:true,passive:true}', PLAYER)
        debug_block = PLAYER[PLAYER.index("const NDS_DEBUG_LIMIT"):PLAYER.index("const dispatchNdsMouse")]
        self.assertNotIn("preventDefault", debug_block)
        self.assertNotIn("setPointerCapture", debug_block)
        self.assertNotIn("dispatchEvent", debug_block)
        self.assertNotIn("getComputedStyle", debug_block)
        self.assertIn("activeTouchIds", debug_block)
        self.assertIn("activePointerIds", debug_block)
        self.assertIn("!inside && !trackedTouch && !trackedPointer", debug_block)
        for field in (
            "eventType", "isTrusted", "pointerType", "clientX", "clientY", "pageX", "pageY",
            "target", "pointerCaptureOwner", "canvasRect", "canvasBackingWidth", "canvasBackingHeight",
            "canvasCssWidth", "canvasCssHeight", "devicePixelRatio", "mappedX", "mappedY",
            "normalizedX", "normalizedY", "movementX", "movementY", "orientation", "viewportOrientation",
            "screenOrientation", "fullscreen", "touchVariant", "activeCore", "configuredCore", "runtimeCore",
            "composedPath", "touchesLength", "targetTouchesLength", "changedTouchesLength",
        ):
            self.assertIn(field, debug_block)
        self.assertIn("const recordNdsDebugAction", PLAYER)
        for field in ("moveCount", "durationMs", "duplicateSuppressionReason", "synthetic-${type}"):
            self.assertIn(field, PLAYER)
        for field in ("logical-down", "logical-up", "logical-cancel", "non-owner-touch"):
            self.assertIn(field, NDS_TOUCH)

    def test_core_storage_is_emulatorjs_indexeddb_and_report_first(self):
        for source in (PLAYER, OFFLINE):
            self.assertIn('indexedDB.open("EmulatorJS-core",1)', source)
            self.assertIn('transaction("core"', source)
            self.assertIn('"?EJS_KEYS!"', source)
        self.assertIn("report?.options?.defaultWebGL2", PLAYER)
        self.assertIn("putCoreRecord(coreFile,coreData,report.buildStart)", PLAYER)
        self.assertIn("an3-arcade-cores-v1", PLAYER)
        self.assertIn('const CORE_CACHE = "an3-arcade-cores-v1"', SERVICE_WORKER)

    def test_performance_polish_keeps_roms_out_of_pwa_cache_and_player_timers_bounded(self):
        self.assertIn('url.pathname.startsWith("/download/")', SERVICE_WORKER)
        self.assertIn('const shellMatchOptions=', SERVICE_WORKER)
        self.assertIn('{ignoreSearch:true}', SERVICE_WORKER)
        self.assertIn('const coreInventory = async () =>', OFFLINE)
        self.assertIn('const cachedCoreEntries = async () =>', OFFLINE)
        self.assertNotIn('response.clone().arrayBuffer()', OFFLINE)
        self.assertIn('navigator.serviceWorker.register(`/service-worker.js?v=${encodeURIComponent(version)}`)', OFFLINE)
        self.assertIn('const clearBootstrapTimers = () =>', PLAYER)
        self.assertIn('addEventListener("pagehide", () => { clearBootstrapTimers();playerSession?.framePacing.stop(); }', PLAYER)
        self.assertIn('let virtualPadGuardTimer = 0;', PLAYER)
        self.assertIn('const slotGetMany = slots => requireQuickSaves().getMany(slots);', PLAYER)
        self.assertIn('const libraryCards = [...document.querySelectorAll("#gameGrid .game-card")]', SITE_JS)
        self.assertIn('const scheduleLibraryFilter = () =>', SITE_JS)
        self.assertIn('const scheduleLibraryVersionCheck = (delay = 60000)', SITE_JS)
        self.assertIn('protocol_version = "HTTP/1.1"', APP)
        self.assertIn('conn.execute("PRAGMA journal_mode=WAL")', APP)
        self.assertIn('public_resource = (', APP)
        self.assertIn('public,max-age=31536000,immutable', APP)

    def test_nds_delivery_keeps_original_archive_and_range_support(self):
        self.assertIn('path.startswith("/game-file/") and game["system"] != "nds"', APP)
        self.assertIn('if game["system"] not in {"gb", "gba"}', APP)
        self.assertIn('self.send_header("Accept-Ranges", "bytes")', APP)
        self.assertIn('self.send_header("Content-Range", f"bytes {start}-{end}/{size}")', APP)


if __name__ == "__main__":
    unittest.main(verbosity=2)
